# ./.github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Futtassa a workflow-t, amikor pusholsz a 'main' branch-re (vagy amit használsz)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # A build futtató környezete (Linux)

    # IDE ADD HOZZÁ EZT A BLOKKOT, HA MÉG NINCS:
    permissions:
      contents: write # Ennek engedélyeznie kell a GITHUB_TOKEN-nek az írási jogot a repositoryhoz.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Vagy a projekt Node.js verziója

      - name: Install dependencies
        run: npm install

      - name: Build project # Ez a lépés hozza létre a 'dist' mappát
        run: npm run build
        # IDE VAN A JAVÍTÁS: Környezeti változók átadása a build lépésnek
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # A buildelt fájlok mappája
          publish_branch: gh-pages
          # allow_empty_commit: false # Ezt hagyd defaulton vagy távolítsd el, ha nincs explicit ok rá
          # keep_files: false # Ezek is defaulton vannak
          # force_orphan: false # És ezek is
          # enable_jekyll: false
          # disable_nojekyll: false
          # exclude_assets: .github
