# ./.github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Futtassa a workflow-t, amikor pusholsz a 'main' branch-re (vagy amit használsz)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # A build futtató környezete (Linux)

    steps:
      - name: Checkout code # 1. Lépés: Kód letöltése a repositoryból
        uses: actions/checkout@v3 # Használja a GitHub Action "checkout"-ot

      - name: Setup Node.js # 2. Lépés: Node.js környezet beállítása
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajánlott: Használd a projekt Node.js verzióját

      - name: Install dependencies # 3. Lépés: Függőségek telepítése
        run: npm install # Futtatja az npm install parancsot

      - name: Build project # 4. Lépés: Projekt buildelése (létrehozza a 'dist' mappát)
        run: npm run build # Futtatja a 'build' szkriptet a package.json-ból

      - name: Deploy to GitHub Pages # 5. Lépés: Deployolás GitHub Pages-re
        uses: peaceiris/actions-gh-pages@v3 # Harmadik féltől származó Action a deployhoz
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub által generált automatikus token
          publish_dir: ./dist # A buildelt fájlok mappája
          publish_branch: gh-pages # A branch, ahová a GitHub Pages fogja feltölteni a fájlokat
                                   # Ha ez a branch nem létezik, az Action létrehozza.
